/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package {{cookiecutter.java_package_name}}

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
